# Generated by Django 3.1.6 on 2021-05-05 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Serviceuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, null=True)),
                ('lastname', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='profile.png', null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Serviceprovider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('nin', models.CharField(max_length=200)),
                ('dob', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200)),
                ('phyadd', models.CharField(max_length=200)),
                ('yearexp', models.CharField(max_length=200)),
                ('notmidman', models.CharField(max_length=200)),
                ('skillset', models.CharField(max_length=200)),
                ('internet', models.CharField(max_length=200)),
                ('qualification', models.CharField(max_length=200)),
                ('portifolio', models.CharField(blank=True, max_length=200)),
                ('profession', models.CharField(max_length=200)),
                ('ref1name', models.CharField(max_length=200)),
                ('ref1title', models.CharField(max_length=200)),
                ('ref1email', models.EmailField(max_length=200)),
                ('ref1phone', models.CharField(max_length=200)),
                ('ref2name', models.CharField(max_length=200)),
                ('ref2title', models.CharField(max_length=200)),
                ('ref2email', models.EmailField(max_length=200)),
                ('ref2phone', models.CharField(max_length=200)),
                ('service', models.CharField(choices=[('Personal Support Assistance', 'Personal Support Assistance'), ('Ugandan Sign Language Interpreter', 'Ugandan Sign Language Interpreter'), ('International Sign Language Interpreter', 'International Sign Language Interpreter'), ('Captioning', 'Captioning'), ('Mobility Guide', 'Mobility Guide')], max_length=200, null=True)),
                ('availability', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Suspended', 'Suspended')], max_length=200, null=True)),
                ('starttime', models.CharField(max_length=200)),
                ('endtime', models.CharField(max_length=200)),
                ('pricevisit', models.CharField(max_length=200)),
                ('terms', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('meetplace', models.CharField(max_length=200, null=True)),
                ('meetdate', models.CharField(max_length=200, null=True)),
                ('starttime', models.CharField(max_length=200, null=True)),
                ('endtime', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(blank=True, default='Pending', max_length=200, null=True)),
                ('serviceprovider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.serviceprovider')),
                ('serviceuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.serviceuser')),
            ],
            options={
                'ordering': ['-date_created', 'name'],
            },
        ),
    ]
