# Generated by Django 3.1.6 on 2021-02-24 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Serviceuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Serviceprovider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('nin', models.CharField(max_length=200)),
                ('dob', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('phyadd', models.CharField(max_length=200)),
                ('yearexp', models.CharField(max_length=200)),
                ('notmidman', models.CharField(max_length=200)),
                ('skillset', models.CharField(max_length=200)),
                ('internet', models.CharField(max_length=200)),
                ('qualification', models.CharField(max_length=200)),
                ('portifolio', models.CharField(blank=True, max_length=200)),
                ('profession', models.CharField(max_length=200)),
                ('ref1name', models.CharField(max_length=200)),
                ('ref1title', models.CharField(max_length=200)),
                ('ref1email', models.EmailField(max_length=200)),
                ('ref1phone', models.CharField(max_length=200)),
                ('ref2name', models.CharField(max_length=200)),
                ('ref2title', models.CharField(max_length=200)),
                ('ref2email', models.EmailField(max_length=200)),
                ('ref2phone', models.CharField(max_length=200)),
                ('service', models.CharField(max_length=200)),
                ('sunday', models.CharField(blank=True, max_length=200)),
                ('monday', models.CharField(blank=True, max_length=200)),
                ('tuesday', models.CharField(blank=True, max_length=200)),
                ('wednesday', models.CharField(blank=True, max_length=200)),
                ('thursday', models.CharField(blank=True, max_length=200)),
                ('friday', models.CharField(blank=True, max_length=200)),
                ('saturday', models.CharField(blank=True, max_length=200)),
                ('starttime', models.CharField(max_length=200)),
                ('endtime', models.CharField(max_length=200)),
                ('pricevisit', models.CharField(blank=True, max_length=200)),
                ('terms', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serviceProviders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetplace', models.CharField(max_length=200)),
                ('meetdate', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('starttime', models.CharField(max_length=200)),
                ('endtime', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked'), ('Not available', 'Not available')], max_length=200, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
