# Generated by Django 3.1.6 on 2021-05-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceprovider',
            options={'ordering': ['-date_created', 'fullname']},
        ),
        migrations.AlterModelOptions(
            name='serviceuser',
            options={'ordering': ['-date_created', 'firstname']},
        ),
        migrations.AlterField(
            model_name='serviceuser',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
