# Generated by Django 3.1.6 on 2021-05-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210518_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200, null=True),
        ),
    ]
