# Generated by Django 3.1.6 on 2021-02-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210224_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daysavailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='wednesday',
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=200),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='availability',
            field=models.ManyToManyField(to='profiles.Daysavailable'),
        ),
    ]
