# Generated by Django 3.2.3 on 2021-06-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210607_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='service',
            field=models.CharField(choices=[('Personal Support Assistance', 'Personal Support Assistance'), ('Ugandan Sign Language Interpreter', 'Ugandan Sign Language Interpreter'), ('International Sign Language Interpreter', 'International Sign Language Interpreter'), ('Captioning', 'Captioning'), ('Mobility Guide', 'Mobility Guide'), ('Tactile Sign Language Interpreter', 'Tactile Sign Language Interpreter')], max_length=200, null=True),
        ),
    ]
