# Generated by Django 3.1.6 on 2021-04-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210405_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to=''),
        ),
    ]
