# Generated by Django 3.1.6 on 2021-05-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_serviceuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile.png', upload_to='profilepics/'),
        ),
    ]
