# Generated by Django 3.2.3 on 2021-07-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_serviceprovider_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='qualification',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
