# Generated by Django 3.1.6 on 2021-03-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_serviceuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='endtime',
            field=models.TimeField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='meetdate',
            field=models.DateField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='starttime',
            field=models.TimeField(max_length=200, null=True),
        ),
    ]
