# Generated by Django 3.1.6 on 2021-03-01 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210224_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetplace', models.CharField(max_length=200)),
                ('meetdate', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('starttime', models.CharField(max_length=200)),
                ('endtime', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='availability',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='availability',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Daysavailable',
        ),
        migrations.AddField(
            model_name='booking',
            name='serviceprovider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.serviceprovider'),
        ),
        migrations.AddField(
            model_name='booking',
            name='serviceuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.serviceuser'),
        ),
    ]
