# Generated by Django 3.1.6 on 2021-03-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210324_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='service',
            field=models.CharField(choices=[('Personal Support Assistance', 'Personal Support Assistance'), ('Ugandan Sign Language Interpreter', 'Ugandan Sign Language Interpreter'), ('International Sign Language Interpreter', 'International Sign Language Interpreter'), ('Captioning', 'Captioning'), ('Mobility Guide', 'Mobility Guide')], max_length=200),
        ),
    ]
