# Generated by Django 3.1.6 on 2021-05-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210530_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='endtime',
            field=models.TimeField(max_length=200),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='starttime',
            field=models.TimeField(max_length=200),
        ),
    ]
