# Generated by Django 3.1.6 on 2021-04-26 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20210422_1312'),
        ('profiles', '0002_serviceprovider_status'),
    ]

    operations = [
    ]
