# Generated by Django 3.1.6 on 2021-03-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20210324_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='availability',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
