# Generated by Django 3.1.6 on 2021-03-24 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_serviceprovider_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='availability',
        ),
    ]
