# Generated by Django 3.1.6 on 2021-03-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_remove_serviceprovider_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='wednesday',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='availability',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
